FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app

# Копируем только то, что нужно для сборки
COPY pom.xml .
COPY src/main ./src/main

RUN mvn -B clean package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]